export const links = {
  home: 'https://treasure.lol',
  explorer: 'https://explorer.hyperlane.xyz',
  discord: 'https://discord.com/invite/treasuredao',
  github: 'https://github.com/TreasureProject/hyperlane-warp-ui',
  docs: 'https://docs.treasure.lol',
  warpDocs: 'https://docs.hyperlane.xyz/docs/reference/applications/warp-routes',
  gasDocs: 'https://docs.hyperlane.xyz/docs/reference/hooks/interchain-gas',
  chains: 'https://docs.hyperlane.xyz/docs/resources/domains',
  twitter: 'https://x.com/Treasure_DAO',
  blog: 'https://treasuredao.substack.com',
  tos: 'https://treasure.lol/terms-of-service',
  privacyPolicy: 'https://treasure.lol/privacy-policy',
  bounty: 'https://treasure.lol',
};
